--=== ADDITIONAL PRACTICES ===

--=== 1 ===
INSERT ALL
WHEN SAL < 5000 THEN
INTO special_sal VALUES(EMPID, SAL)
ELSE 
INTO sal_history VALUES(EMPID, HIREDATE, SAL)
INTO mgr_history VALUES(EMPID, MGR, SAL)
SELECT employee_id EMPID, hire_date HIREDATE, salary SAL, manager_id MGR
FROM employees
WHERE employee_id >= 200;

--=== 2 ===
SELECT * FROM special_sal;
SELECT * FROM sal_history;
SELECT * FROM mgr_history;

--=== 3 ===
CREATE TABLE LOCATIONS_NAMED_INDEX
(location_id NUMBER(4) PRIMARY KEY USING INDEX
(CREATE INDEX locations_pk_idx ON 
LOCATIONS_NAMED_INDEX(location_id)),
location_name VARCHAR2(20));

--=== 4 ===
SELECT INDEX_NAME, TABLE_NAME
FROM USER_INDEXES
WHERE TABLE_NAME = 'LOCATIONS_NAMED_INDEX';

--=== 5 ===
ALTER SESSION
SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS';

--=== 6 ===
SELECT TZ_OFFSET ('Australia/Sydney') from dual;
SELECT TZ_OFFSET ('Chile/EasterIsland') from dual;

ALTER SESSION
SET TIME_ZONE = '+10:00';

SELECT SYSDATE, CURRENT_DATE, CURRENT_TIMESTAMP, LOCALTIMESTAMP FROM dual;

ALTER SESSION
SET TIME_ZONE = '-06:00';

SELECT SYSDATE, CURRENT_DATE, CURRENT_TIMESTAMP, LOCALTIMESTAMP FROM dual;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY';

--=== 6 ===
